name: fitnesstracker
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  firebase_core: ^2.25.4
  firebase_storage: ^11.5.3
  file_picker: ^6.1.1
  
  camera: ^0.10.5+7
  permission_handler: ^11.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0
  shared_preferences: ^2.2.2

  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png" # <- replace this with your actual icon path

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/app_icon.png # <- make sure this path is valid and the file exists
